/**
 * Created by GaborK on 02/07/15.
 */


var designers = [ "Gábor Kerekes",
    "Vera Van de Seyp",
    "Rafael Henneberke",
    "Karina Zavidova",
    "Erik van der Veen",
    "Viktoryia Shydlouskaya",
    "Dave Popping",
    "Luc Eggenhuizen",
    "Martijn de Heer",
    "Leeza Pritychenko",
    "Elena Shkarupa",
    "Jorick de Quaasteniet",
    "Hae Won Lim",
    "Oneyoung Baque",
    "Jaap Smit",
    "Znb Bnssr",
    "Carlijn Moerenhout",
    "Lisa van den Heuvel",
    "John van der Meule",
    "Naomi Naus",
    "Amaya Hagelaar",
    "Yara Velosova",
    "Christina Yarashevich",
    "Marloes van den Berg",
    "Caroline Langendoen",
    "Felipe Braz",
    "Caitlin Berner",
    "Veerle Hoefnagels",
    "Peter Palland",
    "Janne van Hooff",
    "Yacinth Pos",
    "Jaen Mirae Fhay",
    "Magda Ma",
    "Maxime Matias",
    "Anna Neva",
    "Ruder Isaac",
    "Leo Ravy",
    "Ada Brzozowska",
    "Caio Reis",
    "Adriaan Mellegers",
    "Nakyung Kim",
    "Joany Scheeve",
    "Jana",
    "Joeri Woudstra",
    "Pauline Baumberger",
    "Octavia Van Horik",
    "Lisa Moret",
    "Débora Marquesi",
    "Marlen Julie",
    "Evelien Broersen",
    "Qianyun Zhang",
    "Laura Adel",
    "Stephanie Schepel",
    "Rob van den Nieuwenhuizen",
    "Sanne Kloppenburg",
    "Joëlle Erkamp",
    "Job Wouters",
    "Eline van der Ploeg",
    "Jeff Pesch",
    "Arthur van Beek",
    "Aukje Dekker",
    "Max Kazemzadeh",
    "Pauline Schep",
    "Jochem Van Der Spek" ];


var graduates = [ "Alexis Schear",
    "Rudy Vandeusen",
    "Emmanuel Willeford",
    "Fidelia Fuentez",
    "Irina Keaney",
    "Nikki Andrus",
    "Malia Fischetti",
    "Sandee Mcclurg",
    "Everette Pineo",
    "Edie Dearman",
    "Carman Jeremiah",
    "Eliana Gartland",
    "Joslyn Buzbee",
    "Hilary Lauritzen",
    "Camie Sanroman",
    "Dori Carrillo",
    "Adeline Hosea",
    "Alysia Cheeseman",
    "Renata Leard",
    "Lashay Shuster",
    "Ralph Kilbourn",
    "Lashawna Swindall",
    "Damaris Sherwood",
    "Mel Esses",
    "Lucile Moralez",
    "Penelope Fraher",
    "Zelma Stanko",
    "Veola Biggerstaff",
    "Kymberly Shue",
    "Carisa Breed",
    "Mariella Cagle",
    "Gena Ruiz",
    "Soo Mcarthur",
    "Emeline Denicola",
    "Waneta Radcliff",
    "Mariette Dougan",
    "Augustus Palomino",
    "Anne Lizarraga",
    "Perla Curtis",
    "Jesenia Mujica",
    "Carlena Westley",
    "Gilbert Tam",
    "Christena Edberg",
    "Elenor Dillenbeck",
    "Carter Fugate",
    "Travis Pelt",
    "Terisa Gokey",
    "Jenny Necaise",
    "Wilhelmina Abler",
    "Numbers Fickel" ];
